### ISSUE TITLE
Region settings not correct.

### ISSUE THREAD

**Issue by hirschi81** [justinstenning/Direct3DHook#77]
I wanted to capture some region from the upper right, but the settings that I've made with the TestScreenshot GUI, did not result in the correct region. I was able to track it down to the file "DXHookD3D11.cs", line 378:
`captureRegion = new Rectangle(this.Request.RegionToCapture.Left, this.Request.RegionToCapture.Top, this.Request.RegionToCapture.Right, this.Request.RegionToCapture.Bottom);`

In order to match with the rectangle constructor I changed it into:
`captureRegion = new Rectangle(this.Request.RegionToCapture.Left, this.Request.RegionToCapture.Top, this.Request.RegionToCapture.Width, this.Request.RegionToCapture.Height);`

Worked for me, and maybe it will help others, too. ;)

**Comment by spazzarama** [comment]
Thanks
