### ISSUE TITLE
Memory leak on image draw

### ISSUE THREAD

**Issue by Sardelka9515** [justinstenning/Direct3DHook#79]
The `Texture2D` created in [this line](https://github.com/justinstenning/Direct3DHook/blob/a110d7fd36de7a2aee20bbc40794928561ac1943/Capture/Hook/DX11/DXSprite.cs#L281) is not being disposed after use, causing potential memory leak.

**Comment by justinstenning** [comment]
That is a pointer to the reference [created here](https://github.com/justinstenning/Direct3DHook/blob/a110d7fd36de7a2aee20bbc40794928561ac1943/Capture/Hook/DX11/DXImage.cs#L93) which is disposed when the DXImage is disposed:

**Comment by justinstenning** [comment]
The overlay was not being disposed, fixed in https://github.com/justinstenning/Direct3DHook/commit/601bc6d778b4a2c84a78633666b7785da9e605ec
